name: Cypress E2E
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress-E2E:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # If you're using actions/checkout@v3 you must set persist-credentials to false in most cases for the deployment to work correctly.
      - uses: actions/setup-node@v3
        with:
          node-version: '18.1.0'
      - run: npm ci
      - uses: cypress-io/github-action@v5
        with:
          start: npm start
          wait-on: 'http://127.0.0.1:3000'
